print("hello world")
print("Testando o Codespasce")
primeiro_nome = input("Digite seu primeiro nome: ")
matricula = input("Digite sua matrícula: ")
print(f"primeiro nome: {primeiro_nome} matrícula: {matricula}")